#### Statistical Modelling

##### Definition of response and predictor variables
- The variable we would like to predict is the _response_ variable, denoted by $Y$ and the individual observations $y_{i}$.
- The variables that the response variable depend on are the _predictor_ or independent variables, denoted by $X = (X_{1}, X_{2},...,X_{p})$ and individual observations as $x_{ij}$, where $i$ indexes the observations 1,...,$n$, and $j$ indexes the predictor variables 1,...,$p$. [Think of observations as rows of a dataframe, and the variables as columns]

##### Statistical model
- Assume that the response variable $Y$ relates to the predictors $X$ by $Y = f(X) + \epsilon$, where $f$ is the unknown function that relates Y to X, and $\epsilon$ is the amount that $Y$ differs from $f(X)$.
- A statistical model is any algorithm that estimates $f$ and we denote the estimator function $\hat f$.

##### Prediction vs estimation
- Inference problems require a set of observations of predictors $(x_{i1}, x_{i2},...,x_{ip})$ to predict a value for the response variable, $\hat y_{i}$ and $\hat y_{i} = \hat f(x_{i1}, x_{i2},...,x_{ip})$. This requires $\hat f$ to be explicitly defined.
- In prediction problems, the form of $\hat f$ does not matter, instead it depends on minimizing $\epsilon$ such that the prediction $\hat y_{i}$ is as close to the observed value $y_{i}$ as possible.
- Some models are more suited for inference, and others for prediction.

##### Regression vs Classification
- There are 2 main types of prediction problems:
  - **Regression problems** are ones with a _quantitative_ response variable, e.g. predicting the number of    cab pick-ups in Singapore.
  - **Classification problems** are ones with a _categorical_ response variable, e.g. predicting whether or not a Netflix user will like a particular movie.
  
##### Loss function
- In order to quantify how well a model performs, we define a loss or error function.
- A common loss function for quantitative outcomes is the **Mean Squared Error (MSE)** $= \frac{1}{n}\sum\limits_{i=1}^n(y_{i} - \hat y_{i})^{2}$, used to calculate the _least squares_ regression line. 
  
##### Linear Regression estimation model
- Linear regression is a **parametric** model with a fixed number of parameters and independent of observed data.
- Aim is to fit a line to the data, using the _least squares_ regression line.
- Assume relationship between $Y$ and $X$ is given by a linear function, $Y = f(X) + \epsilon = \beta_{0} + \beta_{1}X + \epsilon$, where $\beta_{0}$ and $\beta_{1}$ are unknown parameters.
- We compute the estimated regression line, given by $\hat Y = \hat f(X) = \hat\beta_{0} + \hat\beta_{1}X$, where $\hat\beta_{0}$ and $\hat\beta_{1}$ are estimates of $\beta_{0}$ and $\beta_{1}$ respectively.
- Aim is to choose $\hat\beta_{0}$ and $\hat\beta_{1}$ such that $\epsilon$ is minimized, using available observations.
- Using MSE as the loss function, we can find explicit formulae for $\hat\beta_{0}$ and $\hat\beta_{1}$, i.e.
$\hat\beta_{1} = \frac{\sum\limits_{i} (x_{i}-\bar{x})(y_{i}-\bar{y})}{\sum\limits_{i} (x_{i}-\bar{x})^{2}}$, $\hat\beta_{0} = \bar{y}-\hat\beta_{1}\bar{x}$, where $\bar{x}$ and $\bar{y}$ are sample means.
- The line $\hat{Y} = \hat\beta_{0} + \hat\beta_{1}X$ is known as the least squares regression line of $Y$ on $X$.

##### k-Nearest Neighbours (kNN) prediction model
- kNN is a **non-parametric** model whose set of parameters depends entirely on the training set.
- Aim is to predict a response from a set of observed predictor values using the responses of other observations most similar or nearest to it.
- Unlike linear regression, kNN ‘regression’ does not return a single formula but rather a best predicted output value for any given input.
- The predicted response, $\hat y_{i}$ for the $i^{th}$ observation of a predictor variable, $x_{i}$ is the average of the observed responses, $y_{j}$ of the k-closest (in terms of distance between the predictors, $\lvert x_{i}-x_{j} \rvert$) observations, i.e. $\hat y_{i} = \frac{1}{k} \sum\limits_{j=1}^k y_{j}$.
![kNN_pred_ex.PNG](attachment:kNN_pred_ex.PNG)
- Example: Given the dataset below, we wish to predict the outcome (y-value) of a predictor with an observed value of $-0.75$.
<img src="https://miro.medium.com/max/743/1*46cw99E5O3MchLoo-PnSmg.png" width="300" height="300"/>  
- Suppose k=3, then the predicted value will be the average of the observed y-values of the 3 observations identified:  
<img src="https://miro.medium.com/max/743/1*p-57qz76meXyyN-YHDu7bw.png" width="300" height="300"/>
- Imagine doing this for all the possible input values:  
<img src="https://miro.medium.com/max/743/1*zX2QYVA2otYHqVDJrjxl6Q.png" width="300" height="300"/>
- We end up with a 'regression' line:  
<img src="https://miro.medium.com/max/743/1*4A0_oUq9uGKSy3qQDpzX1g.png" width="300" height="300"/>
- If we have multiple predictor variables, we compute the euclidean distance between any two rows of the dataset as vectors, i.e. $\sqrt{\sum_{i=1}^n(x_{1i} – x_{2i})^{2}}$, where $x_{1}$ is the first row of data, $x_{2}$ is the second row of data and $i$ is the index to a specific column as we sum across all columns (**except for the outcome column**).


In [ ]:
install.packages('nycflights13')

Installing package into ‘/home/nbuser/R’
(as ‘lib’ is unspecified)


In [ ]:
install.packages('MASS')

Installing package into ‘/home/nbuser/R’
(as ‘lib’ is unspecified)


##### k-Nearest Neighbours regression example

In [ ]:
# Load the data
data("Boston", package = "MASS")
# Inspect the data and summary
head(Boston); dim(Boston); summary(Boston)

crim    zn indus chas nox   rm    age  dis    rad tax ptratio black  lstat
1 0.00632 18 2.31  0    0.538 6.575 65.2 4.0900 1   296 15.3    396.90 4.98 
2 0.02731  0 7.07  0    0.469 6.421 78.9 4.9671 2   242 17.8    396.90 9.14 
3 0.02729  0 7.07  0    0.469 7.185 61.1 4.9671 2   242 17.8    392.83 4.03 
4 0.03237  0 2.18  0    0.458 6.998 45.8 6.0622 3   222 18.7    394.63 2.94 
5 0.06905  0 2.18  0    0.458 7.147 54.2 6.0622 3   222 18.7    396.90 5.33 
6 0.02985  0 2.18  0    0.458 6.430 58.7 6.0622 3   222 18.7    394.12 5.21 
  medv
1 24.0
2 21.6
3 34.7
4 33.4
5 36.2
6 28.7

[1] 506  14

      crim                zn             indus            chas        
 Min.   : 0.00632   Min.   :  0.00   Min.   : 0.46   Min.   :0.00000  
 1st Qu.: 0.08204   1st Qu.:  0.00   1st Qu.: 5.19   1st Qu.:0.00000  
 Median : 0.25651   Median :  0.00   Median : 9.69   Median :0.00000  
 Mean   : 3.61352   Mean   : 11.36   Mean   :11.14   Mean   :0.06917  
 3rd Qu.: 3.67708   3rd Qu.: 12.50   3rd Qu.:18.10   3rd Qu.:0.00000  
 Max.   :88.97620   Max.   :100.00   Max.   :27.74   Max.   :1.00000  
      nox               rm             age              dis        
 Min.   :0.3850   Min.   :3.561   Min.   :  2.90   Min.   : 1.130  
 1st Qu.:0.4490   1st Qu.:5.886   1st Qu.: 45.02   1st Qu.: 2.100  
 Median :0.5380   Median :6.208   Median : 77.50   Median : 3.207  
 Mean   :0.5547   Mean   :6.285   Mean   : 68.57   Mean   : 3.795  
 3rd Qu.:0.6240   3rd Qu.:6.623   3rd Qu.: 94.08   3rd Qu.: 5.188  
 Max.   :0.8710   Max.   :8.780   Max.   :100.00   Max.   :12.127  
      rad              tax 

In [ ]:
# Split data into training and test sets
# Use sample() to randomly draw a sample of the specified size from the dataset either 
# without replacement or with replacement (same index can appear more than once) and returns a vector of indices
# Syntax: sample(x, size, replace=F, prob=NULL)
# Use 80/20 splitting rule (80% of data for training, 20% for testing)
set.seed(100)  # Set a seed for random number generator to ensure reproducibility
training_idx <- sample(1: nrow(Boston), nrow(Boston)*0.8) 
train_data <- Boston[training_idx, ]; head(train_data)
test_data <- Boston[-training_idx, ]; head(test_data)

crim    zn indus chas nox   rm    age  dis    rad tax ptratio black  lstat
156 3.53501  0 19.58 1    0.871 6.152 82.6 1.7455 5   403 14.7     88.01 15.02
131 0.34006  0 21.89 0    0.624 6.458 98.9 2.1185 4   437 21.2    395.04 12.60
279 0.07978 40  6.41 0    0.447 6.482 32.1 4.1403 4   254 17.6    396.90  7.19
29  0.77299  0  8.14 0    0.538 6.495 94.4 4.4547 4   307 21.0    387.94 12.80
236 0.33045  0  6.20 0    0.507 6.086 61.5 3.6519 8   307 17.4    376.75 10.88
243 0.10290 30  4.93 0    0.428 6.358 52.9 7.0355 6   300 16.6    372.75 11.22
    medv
156 15.6
131 19.2
279 29.1
29  18.4
236 24.0
243 22.2

crim    zn   indus chas nox   rm    age   dis    rad tax ptratio black 
1  0.00632 18.0 2.31  0    0.538 6.575  65.2 4.0900 1   296 15.3    396.90
2  0.02731  0.0 7.07  0    0.469 6.421  78.9 4.9671 2   242 17.8    396.90
3  0.02729  0.0 7.07  0    0.469 7.185  61.1 4.9671 2   242 17.8    392.83
6  0.02985  0.0 2.18  0    0.458 6.430  58.7 6.0622 3   222 18.7    394.12
9  0.21124 12.5 7.87  0    0.524 5.631 100.0 6.0821 5   311 15.2    386.63
12 0.11747 12.5 7.87  0    0.524 6.009  82.9 6.2267 5   311 15.2    396.90
   lstat medv
1   4.98 24.0
2   9.14 21.6
3   4.03 34.7
6   5.21 28.7
9  29.93 16.5
12 13.27 18.9

In [ ]:
library(caret) # Load R's ML library

# Use train() function to fit the model on the training set
# Syntax: train(formula, data, method='knn',...,trControl=trainControl(), preProcess=c('center', 'scale'), tuneLength=3)
# Note preProcess=c('center', 'scale') standardizes the data as the distance measure in kNN 
# is sensitive to the predictor's scale. See section 8.2.2 at https://bradleyboehmke.github.io/HOML/knn.html#eq:euclidean
# In general, the formula of a model is specified as y~x1+x2+..., where y is the outcome variable we are
# predicting and x1, x2,... are the predictor variables. tuneLength specifies the number of possible k values to evaluate
# and selects the best one among them.

# See https://kevinzakka.github.io/2016/07/13/k-nearest-neighbor/ on parameter tuning
set.seed(101)  # Set a seed to ensure reproducibility of train()
model <- train(
medv~., data = train_data, method = "knn",  # ~. means all other variables will be used as predictor variables
trControl = trainControl("cv", number = 10), # Note that cross-validation resamples and splits the training set by the specified number of times, choose a number that ensures size of resampled data set >= 50   
preProcess = c("center","scale"),
tuneLength = 10
)
plot(model)

Loading required package: lattice
Loading required package: ggplot2


##### Selecting a k value
- The best k is the one that minimize the prediction error RMSE (root mean squared error).
- RMSE $= \sqrt{\sum\limits_{i=1}^n\frac{(\hat y_{i} - y_{i})^{2}}{n}}$
- train() code above choses a value of k that minimizes the RMSE.


In [ ]:
# Best tuning parameter k that minimize the RMSE
model$bestTune  # best k=11

k 
4 11

In [ ]:
# Make predictions on the test data using predict()
predictions <- predict(model, test_data); head(predictions)

# Compute the prediction error RMSE
RMSE(predictions, test_data$medv)

# To visualize the performance of kNN regression, plot predicted medv vs medv in test_data
plot(test_data$medv, predictions, main="Prediction performance of kNN regression")


[1] 25.41818 24.02727 31.10000 24.88182 19.51818 20.64545

[1] 3.994097

##### Summary of kNN regression
- Remember to standardize the data when performing kNN analysis.
- Test multiple k-values to decide an optimal value for your data. This can be done automatically using train() in the caret package.
- Assess the model performance on test data.
- Advantages: Non-parametric algorithm without assumptions. Parametric models like linear regression has lots of assumptions to be met by data before it can be implemented. 
- Disadvantages: **No explicit model** (we are not able to interpret the effects of predictor variables on the outcome). Computationally intensive, since in order to predict an outcome for a new value (in the test set), it will need to search through all the points in its training set to find the nearest ones.

##### Linear regression example

In [ ]:
# lm() function is used to fit a linear regression model
# Syntax: lm(formula, data,...)

lmodel <- lm(medv~., data=train_data)
summary(lmodel)  # prints summary of model fitting


Call:
lm(formula = medv ~ ., data = train_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-16.2196  -2.7975  -0.5056   1.8928  24.7720 

Coefficients:
              Estimate Std. Error t value Pr(>|t|)    
(Intercept)  38.120555   5.739552   6.642 1.04e-10 ***
crim         -0.132466   0.037478  -3.534 0.000458 ***
zn            0.047857   0.016550   2.892 0.004046 ** 
indus        -0.003342   0.073385  -0.046 0.963696    
chas          3.161216   0.997953   3.168 0.001658 ** 
nox         -18.903744   4.327572  -4.368 1.61e-05 ***
rm            3.555364   0.469046   7.580 2.55e-13 ***
age           0.008808   0.015769   0.559 0.576750    
dis          -1.489876   0.233707  -6.375 5.17e-10 ***
rad           0.315867   0.076072   4.152 4.05e-05 ***
tax          -0.010992   0.004448  -2.471 0.013897 *  
ptratio      -0.901041   0.148842  -6.054 3.33e-09 ***
black         0.008061   0.003282   2.456 0.014484 *  
lstat        -0.584936   0.057900 -10.102  < 2e-16 ***
---
Sig

##### Interpreting the lm() summary
- R-squared value is a measure of fitting performance, the higher the R-squared (as close to $\lvert1\rvert$), the better fitted the model is. 
- R-squared $\approx 0.72$ implies that the linear model using all possible predictor variables in the data set can explain 72% of variation of the outcome, medv. 
- Values under Estimate are the estimated coefficients $\hat\beta$ in the linear regression model $Y = \beta_{0} + \beta_{1}X_{1} +...+ \beta_{p}X_{p} + \epsilon, p = 13$.
- The fitted model based on the training data is $\hat Y = \hat\beta_{0} + \hat\beta_{1}X_{1} +...+ \beta_{p}X_{p}$. 
- The important impacts of predictors for outcome medv are indicated by \* for its significance (by p-value). The more number of *’s, the greater the significance level of the predictor in the model.

In [ ]:
# Make predictions on the test data
predictions <- predict(lmodel, test_data); head(predictions)

# Compute the prediction error RMSE
RMSE(predictions, test_data$medv)

# Visualize the performance of linear regression
plot(test_data$medv, predictions, main="Prediction performance of linear regression")

1        2        3        6        9       12 
30.22312 25.13722 30.65295 25.58483 10.67286 21.49097

[1] 4.251321

RMSE of linear regression is not as good as that of kNN regression. In the case where relationship between outcome and predictors is nonlinear, kNN reg would be better than linear regression.

We can look at the residuals, or the difference between the observed value and the predicted value i.e. ($y_{i} - \hat y_{i}$) to assess if the linear regression model fits the training data well and whether the fitting measure R-squared can be improved.

In [ ]:
# Calculate residuals
residuals(lmodel)

# Create various residual plots
plot(lmodel)
 

156           131           279            29           236 
 -4.510519684  -0.853879771  -1.219789846  -1.314392171  -1.357739881 
          243           407           185           273            85 
 -1.906326085   3.812915987   3.498078469  -4.192510114  -0.863938633 
          310           437           139           197           376 
 -3.448399759  -5.093182923  -0.168363641  -2.795499613 -10.076704067 
          329           101           175           176           337 
 -1.986579262   2.576882303  -4.164835855  -1.357688855  -0.726859538 
          261           345           486           362           203 
 -0.665875062   2.474134405  -1.307184699   0.711572472   5.303677491 
           83           370           423           263           133 
 -1.409569659  15.963370766   1.835801587   8.155505831   2.814137107 
          233           442           166           452           491 
  3.552339259   0.009339855  -0.441464847  -4.230113989   4.813538707 
          419           497           296           464            61 
  3.811358738   5.941754098   0.465717265  -2.599227635   0.606122842 
          155           403           361           384           504 
 -5.241668727  -6.007045877   1.805110722  -0.583529441  -4.008754085 
          227           359           406            96           141 
 -0.243822761  -0.269805603  -1.645431755  -0.513557035   1.059212755 
          151            91           108           125           268 
  1.255354018  -4.682251372  -0.626723371  -1.125664730   9.688999957 
          115            56           104           473            95 
 -6.972051986   4.242948225  -1.323406230   0.515360649  -6.447269409 
          207           288           427           300           493 
  0.898238921  -3.943541609  -6.580591244  -2.884626480   4.007760795 
          158           201           196           454           304 
  7.948870242   2.065172520   9.240587099  -4.491550042   0.381359763 
          180           143           249           471           286 
  4.165501752  -0.448324209   3.046107233  -0.496191686  -5.327048213 
          270           369           333           357            40 
 -5.392343346  24.772000127  -3.933281644  -2.266637624  -0.748954111 
          439           255           390           416            16 
  4.262205205  -2.281563142  -2.770134777  -1.937919755   0.320980688 
          244           308           105           126           306 
 -3.673201811  -4.777999928  -1.735016092  -0.517264024  -2.514913101 
          378            88           149           186           374 
 -6.611022482  -3.899217184   9.316868461   4.908769898   8.344741817 
          161           213            52            13           315 
 -6.387282622  -0.485732675  -3.559829286   1.342208406  -1.809120613 
          477           441            17           146           230 
 -3.877065413  -1.650535946   2.423141915   2.927403882   0.190631145 
          275           389           281             5           410 
 -4.306707289   4.253936042   6.631851777   8.158591052   7.644292027 
          332           319            32            94           379 
 -2.686027918  -1.138374249  -3.868714728  -3.969310028  -2.009940674 
           15           358           283            78           326 
 -1.437656426  -1.712733811   5.240971446  -2.611224843  -0.042074253 
          154           152           182           224           135 
  2.568212716   1.595602973   8.341041423   0.071588315   2.287358394 
           11           392           363           209            39 
 -3.471600085   5.927414026   1.837755406   0.693223898   1.851663110 
           90           323           277           413           216 
 -2.279048237  -2.673027349  -2.858891742  16.410275492   0.617467436 
            7           489           422           171           232 
  0.064648356   3.251815010  -4.211965523  -4.984921887  -1.806034592 
          247           394       

We'll focus on the first graph that shows the residuals on the vertical axis and the fitted $\hat y$ on the horizontal axis (0). If the points are randomly dispersed around the horizontal axis, a linear regression model is appropriate for the data; otherwise, a non-linear model is more appropriate. 

![residual_plots.png](attachment:residual_plots.png)

In this case, it looks like it is possible to improve the model fitting by incorporating quadratic terms.

##### Lab 5 tasks

In [ ]:
library(dplyr)
library(caret)
library(nycflights13)


Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Loading required package: lattice
Loading required package: ggplot2


In [ ]:
head(flights)

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1     1   517      515             2         830      819          
2 2013 1     1   533      529             4         850      830          
3 2013 1     1   542      540             2         923      850          
4 2013 1     1   544      545            -1        1004     1022          
5 2013 1     1   554      600            -6         812      837          
6 2013 1     1   554      558            -4         740      728          
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  11       UA      1545   N14228  EWR    IAH  227      1400     5    15    
2  20       UA      1714   N24211  LGA    IAH  227      1416     5    29    
3  33       AA      1141   N619AA  JFK    MIA  160      1089     5    40    
4 -18       B6       725   N804JB  JFK    BQN  183      1576     5    45    
5 -25       DL       461   N668DN  LGA    ATL  116       762     6     0    
6  12       UA      1696   N39463  EWR    ORD  150       719     5    58    
  time_hour          
1 2013-01-01 05:00:00
2 2013-01-01 05:00:00
3 2013-01-01 05:00:00
4 2013-01-01 05:00:00
5 2013-01-01 06:00:00
6 2013-01-01 05:00:00

In [ ]:
# Prepare data
flights <- mutate(flights, gain=arr_delay-dep_delay)
flights_ua <- flights %>% filter(carrier=='UA', air_time > 550); head(flights_ua)
summary(flights_ua)

# Visualize the relationship
library(ggplot2)
flights_ua %>% select(gain, air_time) %>% ggplot(aes(x=air_time, y=gain)) + geom_point() + geom_smooth()

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1     1   1344     1344            0        2005     1944          
2 2013 1     2   1344     1344            0        1940     1944          
3 2013 1     3   1418     1341           37        2006     1935          
4 2013 1     4   1343     1341            2        1932     1935          
5 2013 1     5   1329     1335           -6        1850     1935          
6 2013 1     6   1353     1341           12        1927     1941          
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  21       UA      15     N76065  EWR    HNL  656      4963     13   44    
2  -4       UA      15     N77066  EWR    HNL  634      4963     13   44    
3  31       UA      15     N76064  EWR    HNL  628      4963     13   41    
4  -3       UA      15     N76065  EWR    HNL  623      4963     13   41    
5 -45       UA      15     N76065  EWR    HNL  600      4963     13   35    
6 -14       UA      15     N69063  EWR    HNL  610      4963     13   41    
  time_hour           gain
1 2013-01-01 13:00:00  21 
2 2013-01-02 13:00:00  -4 
3 2013-01-03 13:00:00  -6 
4 2013-01-04 13:00:00  -5 
5 2013-01-05 13:00:00 -39 
6 2013-01-06 13:00:00 -26

      year          month             day           dep_time    sched_dep_time
 Min.   :2013   Min.   : 1.000   Min.   : 1.00   Min.   : 921   Min.   : 930  
 1st Qu.:2013   1st Qu.: 4.000   1st Qu.: 8.00   1st Qu.:1324   1st Qu.:1325  
 Median :2013   Median : 7.000   Median :16.00   Median :1331   Median :1329  
 Mean   :2013   Mean   : 6.535   Mean   :15.74   Mean   :1289   Mean   :1267  
 3rd Qu.:2013   3rd Qu.:10.000   3rd Qu.:23.00   3rd Qu.:1341   3rd Qu.:1335  
 Max.   :2013   Max.   :12.000   Max.   :31.00   Max.   :1755   Max.   :1344  
   dep_delay         arr_time    sched_arr_time   arr_delay      
 Min.   :-13.00   Min.   :  34   Min.   :1527   Min.   :-70.000  
 1st Qu.: -2.00   1st Qu.:1748   1st Qu.:1801   1st Qu.:-15.000  
 Median :  2.00   Median :1807   Median :1813   Median : -3.000  
 Mean   : 13.52   Mean   :1785   Mean   :1790   Mean   :  3.922  
 3rd Qu.: 11.50   3rd Qu.:1846   3rd Qu.:1836   3rd Qu.:  7.500  
 Max.   :290.00   Max.   :2213   Max.   :1944   Max

`geom_smooth()` using method = 'loess' and formula 'y ~ x'


In [ ]:
# Perform kNN regression

# Split data into training and test sets
flights_ua <- flights_ua %>% select(air_time, gain); flights_ua

set.seed(100)  
trg_idx <- sample(nrow(flights_ua), nrow(flights_ua)*0.8) 
trg_data <- flights_ua[trg_idx, ]; head(trg_data)
test_data_0 <- flights_ua[-trg_idx, ]; head(test_data_0)

air_time gain
1   656       21 
2   634       -4 
3   628       -6 
4   623       -5 
5   600      -39 
6   610      -26 
7   620       -9 
8   645       13 
9   667       45 
10  624       -1 
11  611      -21 
12  614      -26 
13  606      -34 
14  618      -15 
15  613      -11 
16  648       24 
17  645       17 
18  627       -6 
19  601      -42 
20  659       20 
21  642        9 
22  620       -8 
23  639        7 
24  644       26 
25  648       45 
26  635        0 
27  636        5 
28  641       20 
29  621       -9 
30  612      -22 
... ...      ... 
330 604      -21 
331 600      -24 
332 593       -9 
333 602      -16 
334 591      -24 
335 580      -34 
336 600      -22 
337 582      -41 
338 599      -22 
339 599      -22 
340 584      -43 
341 612       -1 
342 611      -10 
343 600      -25 
344 607      -13 
345 609      -13 
346 617       -1 
347 614       -5 
348 617       -7 
349 616       -7 
350 611      -11 
351 575      -48 
352 614       -2 
353 601      -23 
354 625        0 
355 628        9 
356 616        9 
357 562      -61 
358 569      -47 
359 604      -17

air_time gain
1 586      -30 
2 619      -21 
3 579      -39 
4 642        9 
5 695       59 
6 643       14

air_time gain
1 656       21 
2 667       45 
3 614      -26 
4 606      -34 
5 648       24 
6 639        7

In [ ]:
# Fit model on training set

set.seed(101)  
flights_model_knn <- train(
gain~., data = trg_data, method = "knn",  
trControl = trainControl("cv", number = 10),  
preProcess = c("center","scale"),
tuneLength = 10
)
plot(flights_model_knn)

# Best tuning parameter k that minimize the RMSE
flights_model_knn$bestTune   # best k=15

k 
6 15

In [ ]:
# Make predictions on the test data
flight_predictions <- predict(flights_model_knn, test_data_0); head(flight_predictions)

# Compute the prediction error RMSE
RMSE(flight_predictions, test_data_0$gain)

# To visualize the performance of kNN regression, plot predicted medv vs medv in test_data
plot(test_data_0$gain, flight_predictions, main="Prediction performance of kNN regression")

[1] 22.733333 29.500000 -6.058824 -9.750000 17.333333  5.705882

[1] 13.68007

In [ ]:
# Perform linear regression

flights_lmodel <- lm(gain~., data=trg_data)
summary(flights_lmodel)


Call:
lm(formula = gain ~ ., data = trg_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-24.892  -7.415  -1.412   5.657  86.820 

Coefficients:
             Estimate Std. Error t value Pr(>|t|)    
(Intercept) -504.4369    23.8187  -21.18   <2e-16 ***
air_time       0.8093     0.0389   20.80   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 13.73 on 285 degrees of freedom
Multiple R-squared:  0.6029,	Adjusted R-squared:  0.6015 
F-statistic: 432.7 on 1 and 285 DF,  p-value: < 2.2e-16


The fitted model is gain = $-504.4369 + 0.8093$air_time, with R-squared $\approx$ 0.60, so air_time is linearly correlated with gain

In [ ]:
# Make predictions on the test data
lm_predictions <- predict(flights_lmodel, test_data_0); head(lm_predictions)

# Compute the prediction error RMSE
RMSE(lm_predictions, test_data_0$gain)

# Visualize the performance of linear regression
plot(test_data_0$gain, lm_predictions, main="Prediction performance of linear regression")
plot(x=test_data_0$air_time, y=test_data_0$gain)
abline(flights_lmodel, col='red')  # plot regression line

1          2          3          4          5          6 
 26.448348  35.350388  -7.541259 -14.015470  19.974137  12.690650

[1] 12.94402

From the RMSE and prediction plot, the linear regression model performs better than knn regression.


In [ ]:
# Don't forget to check the residual plots 
plot(flights_lmodel)

From the residual plot, there is a symmetric distribution of points centered around the horizontal axis with no observable trend (other than 3 outliers), implying an adequate fitting of the linear model to the training data. Removing the outliers may improve the model fitting.